Feature/compiler __attribute__
gatzka/cjet pull request #139
Opened 2017-03-16 13:29 UTC by mborch

- made attribute compiler independent, because visual studio doesn't support it
- removed unnecessary inclusions

2017-03-16 15:12 UTC, gatzka requested changes

2017-03-16 15:12 UTC, gatzka commented on src/base64.c
>  #include "base64.h"
Please order the the includes correctly. First, the includes with <>, then the includes with "".
Separate both blocks with an empty line.

2017-03-16 15:12 UTC, gatzka commented on src/base64.c
> -#include <string.h>
Why took you out string.h? It is required for memcpy().

2017-03-16 15:12 UTC, gatzka commented on src/base64.c
> -#include <stddef.h>
Required for size_t.

2017-03-16 15:12 UTC, gatzka commented on src/base64.c
> -#include <stdint.h>
Required for uint8_t

2017-03-16 15:12 UTC, gatzka commented on src/peer.c
> -#include <arpa/inet.h>
Why have you taken out all these includes? I think the types defined in these headers are used in peer.c

2017-03-16 15:12 UTC, gatzka commented on src/peer.c
> +#include INET
What are is really required from <arpa/inet.h>? I think it just not necessary to include it.

So maybe the whole stuff around INET is not required.

2017-03-16 15:12 UTC, gatzka commented on src/socket_peer.c
> +#include INET
There is already a file jet_endian.h providing the required functions to swap bytes. Use that and kick out <arpa/inet.h>

2017-03-17 12:54 UTC, closed without merging

2017-03-17 12:55 UTC, mborch commented
I will revise it.