Increase max message size
gatzka/cjet pull request #150
Opened 2017-05-19 12:53 UTC by felix-re

Increased read buffer size to 262144 to match the message sizes from autobahn-testsuite. 
The read functions of buffered_socket return 0 now if a problem occures during go_reading, because the error-function handle that. Due to that the unittests has been adaptet and an uninitialized pointer is set now.

2017-05-20 05:33 UTC, gatzka requested changes
Overall good, please make the small requested change.

2017-05-20 05:33 UTC, gatzka commented on src/tests/buffered_socket_test.cpp
> +		readbuffer=buffer;
Please adhere to coding style. (readbuffer = buffer)

2017-05-22 06:33 UTC, felix-re commented on src/tests/buffered_socket_test.cpp
> +		readbuffer=buffer;
done

2017-05-22 14:14 UTC, gatzka approved these changes
Thanks!

2017-05-22 14:15 UTC, merged