Create an UTF8-Checker
gatzka/cjet pull request #156
Opened 2017-06-06 09:30 UTC by felix-re

Create an utf8-checker for text and byte sequences and unit-tests for it. The websocket-peer can use it to validate the incoming text messages and frames. Add it qbs and cmake build files.

2017-06-06 09:36 UTC, felix-re commented
I'm fixing the build problems

2017-06-06 11:51 UTC, felix-re commented
All build problems solved. Ready to review.

2017-06-06 15:05 UTC, gatzka requested changes

2017-06-06 15:05 UTC, gatzka commented on src/tests/utf8_checker_test.cpp
> +																 {0x80,0x00,0x00,0x00},	//invalid start
What an awful bunch of empty lines.
Please reduce that.

2017-06-06 15:05 UTC, gatzka commented on src/tests/utf8_checker_test.cpp
> +	for (uint i = 0; i < sizeof(valid_message_long) - 1; i++) {
Why uint and not unsigned int?

2017-06-06 15:05 UTC, gatzka commented on src/tests/utf8_checker_test.cpp
> +	for (int i = 0; i < invalid_message_size; i++) {
Please use an unsigned int also.

2017-06-06 15:05 UTC, gatzka commented on src/tests/utf8_checker_test.cpp
> +	for (int i = 0; i < invalid_message_size; i++) {
unsigned int.

2017-06-06 15:05 UTC, gatzka commented on src/utf8_checker.c
> +#include "utf8_checker.h"
include <stdbool.h>, >stdint> is missing.

2017-06-06 15:05 UTC, gatzka commented on src/utf8_checker.c
> +#define UC_FINISH 0xFF
Possible to use an const uint8_t?

2017-06-06 15:05 UTC, gatzka commented on src/utf8_checker.c
> +	int finished = 0;
Why not using a bool?

2017-06-06 15:05 UTC, gatzka commented on src/utf8_checker.c
> +	for (unsigned int i = 0; i < length; i++) {
Please use an size_t, to have the same type when comparing to length.

2017-06-07 08:16 UTC, felix-re commented on src/tests/utf8_checker_test.cpp
> +																 {0x80,0x00,0x00,0x00},	//invalid start
replaced tabs with spaces

2017-06-07 08:22 UTC, felix-re commented on src/tests/utf8_checker_test.cpp
> +	for (uint i = 0; i < sizeof(valid_message_long) - 1; i++) {
Didn't know, that it's just a typedef.

2017-06-07 08:22 UTC, felix-re commented on src/tests/utf8_checker_test.cpp
> +	for (int i = 0; i < invalid_message_size; i++) {
done

2017-06-07 08:23 UTC, felix-re commented on src/tests/utf8_checker_test.cpp
> +	for (int i = 0; i < invalid_message_size; i++) {
done

2017-06-07 08:25 UTC, felix-re commented on src/utf8_checker.c
> +#include "utf8_checker.h"
Included, but isn't it sufficient to include it in the header?

2017-06-07 08:27 UTC, felix-re commented on src/utf8_checker.c
> +#define UC_FINISH 0xFF
yes

2017-06-07 08:29 UTC, felix-re commented on src/utf8_checker.c
> +	int finished = 0;
Overlooked, when included stdbool.h

2017-06-07 08:38 UTC, felix-re commented on src/utf8_checker.c
> +	for (unsigned int i = 0; i < length; i++) {
done

2017-06-08 06:13 UTC, gatzka approved these changes

2017-06-08 06:14 UTC, merged