Autobahn Test Merge
gatzka/cjet pull request #158
Opened 2017-06-09 09:15 UTC by felix-re

Includes all files needed to execute the autobahn testsuite and test the websocket implementation

2017-06-19 09:27 UTC, gatzka requested changes
Overall good, some minor coding style stuff.
The only thing that needs real rework is to create an own struct ab_ws_peer to eliminate the global variables like buffers.

2017-06-19 09:27 UTC, gatzka commented on src/CMakeLists.txt
> +	utf8_checker.c
Fix indentation by using spaces instead of tabs.

2017-06-19 09:27 UTC, gatzka commented on src/autobahnfiles/abMain.c
> +        .request_target = "/",  //"/api/jet/",
Please fix indentation.

2017-06-19 09:27 UTC, gatzka commented on src/autobahnfiles/abMain.c
> +            config.bind_local_only = false;
Please fix indentation.

2017-06-19 09:27 UTC, gatzka commented on src/autobahnfiles/abMain.c
> +            .run = eventloop_epoll_run,
Please fix indentation.

2017-06-19 09:27 UTC, gatzka commented on src/autobahnfiles/abWebsocket_peer.c
> +#define WS_CONTINUATION_FRAME 0x0
For what do you need the WS_-defines in this file?

2017-06-19 09:27 UTC, gatzka commented on src/autobahnfiles/abWebsocket_peer.c
> +struct cjet_utf8_checker *checker_ptr;
Why not just using &checker instead of checker_ptr?

2017-06-19 09:27 UTC, gatzka commented on src/autobahnfiles/abWebsocket_peer.c
> +uint8_t *binary_frame_buffer = NULL;
I think all these globals can be made static to not spoiling the global namespace.

In addition, it is a bit ugly that is global at all. I think all theses variables should be members of the peer. To do this you have to write your own struct ab_ws_peer which contains all these variables.

2017-06-19 09:27 UTC, gatzka commented on src/tests/utf8_checker_test.cpp
> +BOOST_AUTO_TEST_CASE(test_message_zero_length)
Using BOOST_FIXTURE_TEST_CASE you don't have to write F f yourself and you have access to all F members automatically.

2017-06-19 09:27 UTC, gatzka commented on src/tests/utf8_checker_test.cpp
> +	int ret;
ret could be declared inside the loop

2017-06-19 09:27 UTC, gatzka commented on src/tests/websocket_frame_test.cpp
> +
Take out empty line.

2017-06-19 09:27 UTC, gatzka commented on src/tests/websocket_frame_test.cpp
> +	char message [] = "Hello World!";
Reduce scope of variable.

2017-06-20 08:38 UTC, felix-re commented on src/CMakeLists.txt
> +	utf8_checker.c
done

2017-06-20 08:38 UTC, felix-re commented on src/autobahnfiles/abMain.c
> +        .request_target = "/",  //"/api/jet/",
done

2017-06-20 08:38 UTC, felix-re commented on src/autobahnfiles/abMain.c
> +            config.bind_local_only = false;
done

2017-06-20 08:39 UTC, felix-re commented on src/autobahnfiles/abMain.c
> +            .run = eventloop_epoll_run,
done

2017-06-20 08:50 UTC, felix-re commented on src/autobahnfiles/abWebsocket_peer.c
> +#define WS_CONTINUATION_FRAME 0x0
relics from websocket.c, they're not used anymore.
Completely removed.

2017-06-20 12:01 UTC, felix-re commented on src/autobahnfiles/abWebsocket_peer.c
> +struct cjet_utf8_checker *checker_ptr;
done

2017-06-20 12:02 UTC, felix-re commented on src/autobahnfiles/abWebsocket_peer.c
> +uint8_t *binary_frame_buffer = NULL;
done

2017-06-20 12:10 UTC, felix-re commented on src/tests/utf8_checker_test.cpp
> +BOOST_AUTO_TEST_CASE(test_message_zero_length)
done

2017-06-20 12:12 UTC, felix-re commented on src/tests/utf8_checker_test.cpp
> +	int ret;
done

2017-06-20 12:13 UTC, felix-re commented on src/tests/websocket_frame_test.cpp
> +
done

2017-06-20 12:20 UTC, felix-re commented on src/tests/websocket_frame_test.cpp
> +	char message [] = "Hello World!";
Do you mean remove empty line?

2017-06-21 08:53 UTC, gatzka requested changes
No further objections, please just add the missing include.

2017-06-21 08:53 UTC, gatzka commented on src/autobahnfiles/abWebsocket_peer.h
> +
#include <stddef.h> is missing. It's necessary for size_t.

2017-06-21 11:07 UTC, felix-re commented on src/autobahnfiles/abWebsocket_peer.h
> +
thanks, done

2017-06-21 12:14 UTC, merged